# -*- coding: utf-8 -*-
"""Copy of List Comprehension CS3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18bohF2fipGLwLDZ2AsdwHj8mxB4cFuc8
"""

x = [i for i in range(15)]
x

a = [4,6,7,3,2]
b = [x*2 for x in a if x > 5]

my_list = [2, 5, 8, 11, 15]
new_list = [x*2 if x < 10 else x+1 for x in my_list]
print(new_list)

my_list = [i for i in range(1, 30) if i%2==0 if i%5==0]
print(my_list)

names = ['Ch','Dh','Eh','cb','Tb','Td']
new_names = [name for name in names if name.lower().startswith('c')]
new_names

new_list = [num * 2 for num in range(5)]
new_list

new_list = [num for num in range(50) if  num > 20 and num % 2 == 0]
new_list

fave_language_chars = [letter for letter in "Python"]
fave_language_chars

# Find all of the numbers from 1-1000 that are divisible by 7
my_list = [i for i in range(1, 1000) if i%7==0]
my_list

#Find all of the numbers from 1-1000 that have a 3 in them
my_list = [i for i in range(1, 1000) if '3' in str(i) ]
my_list

#Count the number of spaces in a string
sentence = 'the slow solid squid swam sumptuously through the slimy swamp'
my_list = [i for i in sentence if i==' ']
print(len(my_list))

# Create a list of all the consonants in the string "Yellow Yaks like yelling and yawning and yesturday they yodled while eating yuky yams"
sentence = "Yellow Yaks like yelling and yawning and yesturday they yodled while eating yuky yams"
my_list = [i for i in sentence if i not in 'a,e,i,o,u, ']
my_list

# Get the index and the value as a tuple for items in the list ["hi", 4, 8.99, 'apple', ('t,b','n')].  Result would look like [(index, value), (index, value)]
v =[ 'a','e','i','o','u',' ' ]
r = [(i,j) for i,j in enumerate(v)]
r

# Find the common numbers in two lists (without using a tuple or set) list_a = [1, 2, 3, 4], list_b = [2, 3, 4, 5]
list_a = [1, 2, 3, 4]
list_b = [2, 3, 4, 5]
com = [i for i in list_a if i in list_b]
com

# Get only the numbers in a sentence like 'In 1984 there were 13 instances9 of a protest with over 1000 people attending'.  Result is a list of numbers like [3,4,5]
sentence = 'In 1984 there were 13 instances of a protest with over 1000 people attending'
word = sentence.split( )
com = [i for i in word if not i.isalpha()]
com

# Produce a list of tuples consisting of only the matching numbers in these lists list_a = [1, 2, 3,4,5,6,7,8,9], list_b = [2, 7, 1, 12].  Result would look like (4,4), (12,12)
list_a = [1, 2, 3,4,5,6,7,8,9]
list_b = [2, 7, 1, 12]
com = [i for i in list_a if i in list_b]
com

'''Find all of the words in a string that are less than 4 letters'''
new_list = [num * 2 for num in range(1,11)]
new_list

new_list = [num**3 for num in range(1,11)]
new_list