# -*- coding: utf-8 -*-
"""List Comprehension VY.1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MX4c-9kiW2oy3UUuNAtL8c3G4U3e9KN4
"""

x = [i for i in range(15)] 
print(x)

a = [4,6,7,3,2]
b = [x*2 for x in a if x > 5]
print(b)

my_list = [2, 5, 8, 11, 15]
new_list = [x*2 if x < 10 else x+1 for x in my_list]
print(new_list)

my_list = [i for i in range(1, 30) if i%2==0 if i%5==0]
print(my_list)

names = ['Ch','Dh','Eh','cb','Tb','Td']
new_names = [name for name in names if name.lower().startswith('c')]
print(new_names)

new_list = [num * 2 for num in range(5)]
print(new_list)

new_list = [num for num in range(50) if  num > 20 and num % 2 == 0]
print(new_list)

fave_language_chars = [letter for letter in "Python"]
print(fave_language_chars)

'''
Find all of the numbers from 1-1000 that are divisible by 7
'''
new_list = [num for num in range(1 , 1001) if  num % 7 == 0]
print(new_list)

'''
Find all of the numbers from 1-1000 that have a 3 in them
'''
new_list = [num for num in range(1 , 1001) if '3' in str(num)]
print(new_list)

'''
Count the number of spaces in a string
'''
some_string = 'the slow solid squid swam sumptuously through the slimy swamp'
space = [ch for ch in some_string if ch == ' ']
len(space)

'''
Create a list of all the consonants in the string "Yellow Yaks like yelling and yawning and yesturday they yodled while eating yuky yams"
'''
sentence = "Yellow Yaks like yelling and yawning and yesturday they yodled while eating yuky yams"
vowel = [ 'a', 'e', 'i', 'o', 'u']
consonants = [ch for ch in sentence if ch.lower() not in vowel]
print(consonants)

'''
 Get the index and the value as a tuple for items in the list ["hi", 4, 8.99, 'apple', ('t,b','n')].  Result would look like [(index, value), (index, value)]
 '''
vowel = [ 'a', 'e', 'i', 'o', 'u']
r = [(i, j) for i, j in enumerate(vowel)]
print(r)

'''
Find the common numbers in two lists (without using a tuple or set) list_a = [1, 2, 3, 4], list_b = [2, 3, 4, 5]
'''
list_a = [1, 2, 3, 4]
list_b = [2, 3, 4, 5]
common = [ch for ch in list_a if ch in list_b]
print(common)

'''
Get only the numbers in a sentence like 'In 1984 there were 13 instances of a protest with over 1000 people attending'.  Result is a list of numbers like [3,4,5]
'''
sentence = 'In 1984 there were 13 instances of a protest with over 1000 people attending'
sen = sentence.split()
num = [ch for ch in sen if ch>='0' and ch<='9']
print(num)

'''
Produce a list of tuples consisting of only the matching numbers in these lists list_a = [1, 2, 3,4,5,6,7,8,9], list_b = [2, 7, 1, 12].  Result would look like (4,4), (12,12)
'''
list_a = [1, 2, 3, 4]
list_b = [2, 3, 4, 5]
common = [(i, i) for i in list_a if i in list_b]
print(common)

'''Find all of the words in a string that are less than 4 letters'''
sentence = 'On a summer day somner smith went simming in the sun and his red skin stung'
sen = sentence.split()
num = [ch for ch in sen if len(ch)<4]
print(num)

'''Cube of list'''
list_a = [1, 2, 3, 4]
cube = [ch*ch*ch for ch in list_a]
print(cube)

'''Table of 2'''
c = [ch*2 for ch in range(1, 11)]
print(c)